name: tugasmobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  # Library untuk bahasa Indonesia (DatePicker, dll)
  flutter_localizations:
    sdk: flutter
  # Library untuk format tanggal dan jam
  hijri: ^3.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Pastikan file foto ini memang ada di folder assets
  assets:
    - assets/foto_kelompok.jpeg